FROM node:20-alpine AS deps

WORKDIR /app

# Copy and install packages
COPY package*.json ./
RUN npm install

FROM node:20-alpine AS dev

WORKDIR /app

# Copy node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy source code
COPY . .

# React dev server port
ENV PORT=5173

# Hot reload for polling
ENV CHOKIDAR_USEPOLLING=false

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]